server:
  port: 8484

spring:
  application:
    name: project-reservations
  data:
    mongodb:
      uri: mongodb+srv://admin:passw0rd@cluster0.okfa3kr.mongodb.net/reservations?retryWrites=true&w=majority
  datasource:
    password: Lovelace
    url: jdbc:postgresql://localhost:5432/reservaciones
    username: ada
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: trace

application:
  security:
    jwt:
      secret-key: d5608c2a97c84dd0c0e0374ab865a131e0305df3f642ff83a03d796d748ac251
      expiration: 86400000
